### ISSUE TITLE
Create a wireframe for our mainpage

### ISSUE THREAD

**Issue by ProRichyMan** [Reem57/flask_portfolio#3]
- [x] Design a layout for our mainpage
- [x] Write notes and include details about backgrounds, colors and button placements
- [x] Include where to place text and what it should say

**Comment by Danny4w** [comment]
[Wireframe Design](https://docs.google.com/document/d/1tb-dejgl3LDyOKPLLTXAAF7qAneWY_KO6omHmS9C-_Y/edit?usp=sharing)
